// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

public interface ActionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.ActionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 user = 1;</code>
   */
  int getUser();
}
