// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

public interface ChangeNickRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.ChangeNickRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 user = 1;</code>
   */
  int getUser();

  /**
   * <code>optional string newNickname = 2;</code>
   */
  java.lang.String getNewNickname();
  /**
   * <code>optional string newNickname = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewNicknameBytes();
}
