// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

/**
 * Protobuf type {@code if4031.ChangeNickRequest}
 */
public  final class ChangeNickRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:if4031.ChangeNickRequest)
    ChangeNickRequestOrBuilder {
  // Use ChangeNickRequest.newBuilder() to construct.
  private ChangeNickRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChangeNickRequest() {
    user_ = 0;
    newNickname_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ChangeNickRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            user_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            newNickname_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return if4031.common.IRCServiceOuterClass.internal_static_if4031_ChangeNickRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return if4031.common.IRCServiceOuterClass.internal_static_if4031_ChangeNickRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            if4031.common.ChangeNickRequest.class, if4031.common.ChangeNickRequest.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 1;
  private int user_;
  /**
   * <code>optional int32 user = 1;</code>
   */
  public int getUser() {
    return user_;
  }

  public static final int NEWNICKNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object newNickname_;
  /**
   * <code>optional string newNickname = 2;</code>
   */
  public java.lang.String getNewNickname() {
    java.lang.Object ref = newNickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newNickname_ = s;
      return s;
    }
  }
  /**
   * <code>optional string newNickname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNewNicknameBytes() {
    java.lang.Object ref = newNickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newNickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (user_ != 0) {
      output.writeInt32(1, user_);
    }
    if (!getNewNicknameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, newNickname_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (user_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, user_);
    }
    if (!getNewNicknameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, newNickname_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static if4031.common.ChangeNickRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static if4031.common.ChangeNickRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static if4031.common.ChangeNickRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static if4031.common.ChangeNickRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static if4031.common.ChangeNickRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static if4031.common.ChangeNickRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static if4031.common.ChangeNickRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static if4031.common.ChangeNickRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static if4031.common.ChangeNickRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static if4031.common.ChangeNickRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(if4031.common.ChangeNickRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code if4031.ChangeNickRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:if4031.ChangeNickRequest)
      if4031.common.ChangeNickRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return if4031.common.IRCServiceOuterClass.internal_static_if4031_ChangeNickRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return if4031.common.IRCServiceOuterClass.internal_static_if4031_ChangeNickRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              if4031.common.ChangeNickRequest.class, if4031.common.ChangeNickRequest.Builder.class);
    }

    // Construct using if4031.common.ChangeNickRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      user_ = 0;

      newNickname_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return if4031.common.IRCServiceOuterClass.internal_static_if4031_ChangeNickRequest_descriptor;
    }

    public if4031.common.ChangeNickRequest getDefaultInstanceForType() {
      return if4031.common.ChangeNickRequest.getDefaultInstance();
    }

    public if4031.common.ChangeNickRequest build() {
      if4031.common.ChangeNickRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public if4031.common.ChangeNickRequest buildPartial() {
      if4031.common.ChangeNickRequest result = new if4031.common.ChangeNickRequest(this);
      result.user_ = user_;
      result.newNickname_ = newNickname_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof if4031.common.ChangeNickRequest) {
        return mergeFrom((if4031.common.ChangeNickRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(if4031.common.ChangeNickRequest other) {
      if (other == if4031.common.ChangeNickRequest.getDefaultInstance()) return this;
      if (other.getUser() != 0) {
        setUser(other.getUser());
      }
      if (!other.getNewNickname().isEmpty()) {
        newNickname_ = other.newNickname_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if4031.common.ChangeNickRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (if4031.common.ChangeNickRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int user_ ;
    /**
     * <code>optional int32 user = 1;</code>
     */
    public int getUser() {
      return user_;
    }
    /**
     * <code>optional int32 user = 1;</code>
     */
    public Builder setUser(int value) {
      
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 user = 1;</code>
     */
    public Builder clearUser() {
      
      user_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object newNickname_ = "";
    /**
     * <code>optional string newNickname = 2;</code>
     */
    public java.lang.String getNewNickname() {
      java.lang.Object ref = newNickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newNickname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string newNickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewNicknameBytes() {
      java.lang.Object ref = newNickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string newNickname = 2;</code>
     */
    public Builder setNewNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newNickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string newNickname = 2;</code>
     */
    public Builder clearNewNickname() {
      
      newNickname_ = getDefaultInstance().getNewNickname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string newNickname = 2;</code>
     */
    public Builder setNewNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newNickname_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:if4031.ChangeNickRequest)
  }

  // @@protoc_insertion_point(class_scope:if4031.ChangeNickRequest)
  private static final if4031.common.ChangeNickRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new if4031.common.ChangeNickRequest();
  }

  public static if4031.common.ChangeNickRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChangeNickRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChangeNickRequest>() {
    public ChangeNickRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ChangeNickRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ChangeNickRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeNickRequest> getParserForType() {
    return PARSER;
  }

  public if4031.common.ChangeNickRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

