// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string nickname = 1;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>optional string nickname = 1;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();
}
