// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 userID = 1;</code>
   */
  int getUserID();

  /**
   * <code>optional .if4031.ResponseStatus status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .if4031.ResponseStatus status = 2;</code>
   */
  if4031.common.ResponseStatus getStatus();

  /**
   * <code>optional string reason = 3;</code>
   */
  java.lang.String getReason();
  /**
   * <code>optional string reason = 3;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
