// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

public interface MessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.MessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .if4031.Message messages = 1;</code>
   */
  java.util.List<if4031.common.Message> 
      getMessagesList();
  /**
   * <code>repeated .if4031.Message messages = 1;</code>
   */
  if4031.common.Message getMessages(int index);
  /**
   * <code>repeated .if4031.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .if4031.Message messages = 1;</code>
   */
  java.util.List<? extends if4031.common.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .if4031.Message messages = 1;</code>
   */
  if4031.common.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
