// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRCService.proto

package if4031.common;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:if4031.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 user = 1;</code>
   */
  int getUser();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
